AWSTemplateFormatVersion: "2010-09-09"
Description: Rekognition Project - Network Layer (VPC, Subnets, NAT, SG)

Parameters:
  ProjectName:
    Type: String
    Default: rekognition-project

  Environment:
    Type: String
    Default: dev

Resources:
  # ---------------------------
  # VPC
  # ---------------------------
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-${Environment}-vpc"

  # ---------------------------
  # Internet Gateway
  # ---------------------------
  InternetGateway:
    Type: AWS::EC2::InternetGateway

  GatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway

  # ---------------------------
  # Subnets (same AZ for public + private)
  # ---------------------------
  PublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.1.0/24
      AvailabilityZone: !Select [ 0, !GetAZs "" ]
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-${Environment}-public-subnet"

  PrivateSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.2.0/24
      AvailabilityZone: !Select [ 0, !GetAZs "" ]   # même AZ que public
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-${Environment}-private-subnet"

  # ---------------------------
  # Public Route table
  # ---------------------------
  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC

  InternetRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

  PublicSubnetRoute:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet
      RouteTableId: !Ref PublicRouteTable

  # ---------------------------
  # NAT Gateway for Private Subnet
  # ---------------------------
  NatEIP:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc

  NatGateway:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: !GetAtt NatEIP.AllocationId
      SubnetId: !Ref PublicSubnet
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-${Environment}-nat-gw"

  PrivateRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-${Environment}-private-rt"

  PrivateRouteToNat:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PrivateRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId: !Ref NatGateway

  PrivateSubnetRoute:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PrivateSubnet
      RouteTableId: !Ref PrivateRouteTable

  # ---------------------------
  # Security Groups
  # ---------------------------

  # EC2 Upload Web (Nginx/PHP)
  WebSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow HTTP and SSH
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-${Environment}-web-sg"

  # EC2 Search Web (Node/Socket.io)
  NodeSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow Node/Socket.io port
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3000
          ToPort: 3000
          CidrIp: 0.0.0.0/0

      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-${Environment}-node-sg"

  # SG pour Lambdas en VPC (sortie vers DB, S3 via VPC + NAT)
  LambdaSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for Lambda functions
      VpcId: !Ref VPC
      # pas d'ingress -> les Lambdas initient les connexions
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-${Environment}-lambda-sg"

  # DB EC2 : n'accepte que les connexions venant des Lambdas (port 3306)
  DbSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow MySQL/MariaDB access from Lambdas
      VpcId: !Ref VPC
      SecurityGroupIngress:
        # Lambdas -> DB
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          SourceSecurityGroupId: !Ref LambdaSecurityGroup

        # SSH depuis l'EC2 upload-web (bastion)
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          SourceSecurityGroupId: !Ref WebSecurityGroup
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-${Environment}-db-sg"

Outputs:
  VPCIdOut:
    Value: !Ref VPC
    Description: VPC ID

  PublicSubnetIdOut:
    Value: !Ref PublicSubnet

  PrivateSubnetIdOut:
    Value: !Ref PrivateSubnet

  WebSecurityGroupIdOut:
    Value: !Ref WebSecurityGroup

  NodeSecurityGroupIdOut:
    Value: !Ref NodeSecurityGroup

  DbSecurityGroupIdOut:
    Value: !Ref DbSecurityGroup
    Description: "Security Group for DB EC2 (in private subnet)"

  LambdaSecurityGroupIdOut:
    Value: !Ref LambdaSecurityGroup
    Description: "Security Group for Lambdas in VPC"
