AWSTemplateFormatVersion: "2010-09-09"
Description: Rekognition Project - EC2 Web Server (Nginx + PHP + Node)

Parameters:
  ProjectName:
    Type: String
    Default: rekognition-project

  Environment:
    Type: String
    Default: dev

  VPCId:
    Type: String

  PublicSubnetId:
    Type: String

  WebSecurityGroupId:
    Type: String

  NodeSecurityGroupId:
    Type: String

  EC2KeyPairName:
    Type: String
    Description: "KeyPair to SSH into EC2"

  GitRepositoryUrl:
    Type: String
    Description: "Your GitHub repo HTTPS URL"

  BranchName:
    Type: String
    Default: "main"

Resources:
  EC2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref EC2Role

  EC2Role:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-${Environment}-ec2-role"

  WebServerEC2:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.micro
      ImageId: ami-0e86e20dae9224db8 # Amazon Linux 2023 (adjust for region)
      KeyName: !Ref EC2KeyPairName
      SubnetId: !Ref PublicSubnetId
      SecurityGroupIds:
        - !Ref WebSecurityGroupId
        - !Ref NodeSecurityGroupId
      IamInstanceProfile: !Ref EC2InstanceProfile
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-${Environment}-web-server"
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          yum update -y

          # Install Git
          yum install -y git

          # Install PHP + Composer + Nginx
          amazon-linux-extras install -y php8.2
          yum install -y nginx

          # Install Node.js 18
          curl -fsSL https://rpm.nodesource.com/setup_18.x | bash -
          yum install -y nodejs

          systemctl enable nginx
          systemctl start nginx

          # Clone the repo
          cd /var/www
          git clone ${GitRepositoryUrl} rekognition-project
          cd rekognition-project
          git checkout ${BranchName}

          # -----------------------
          # PHP app (upload-web)
          # -----------------------
          cd /var/www/rekognition-project/apps/upload-web
          curl -sS https://getcomposer.org/installer | php
          php composer.phar install --no-dev

          # Configure Nginx
          cat >/etc/nginx/nginx.conf <<'EOF'
          user nginx;
          worker_processes auto;
          error_log /var/log/nginx/error.log;
          pid /run/nginx.pid;

          events {
              worker_connections 1024;
          }

          http {
              include /etc/nginx/mime.types;
              default_type application/octet-stream;

              sendfile on;
              keepalive_timeout 65;

              server {
                  listen 80;
                  server_name _;

                  root /var/www/rekognition-project/apps/upload-web/public;
                  index index.php index.html;

                  location / {
                      try_files $uri /index.php?$query_string;
                  }

                  location ~ \.php$ {
                      fastcgi_pass unix:/run/php-fpm/www.sock;
                      fastcgi_index index.php;
                      include fastcgi_params;
                      fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
                  }
              }
          }
          EOF

          systemctl restart nginx

          # -----------------------
          # Node.js app (search-web)
          # -----------------------
          cd /var/www/rekognition-project/apps/search-web
          npm install

          # Create systemd service
          cat >/etc/systemd/system/search-web.service <<'EOF'
          [Unit]
          Description=Search Web (Node.js + Socket.io)
          After=network.target

          [Service]
          Type=simple
          WorkingDirectory=/var/www/rekognition-project/apps/search-web
          ExecStart=/usr/bin/node server.js
          Restart=always
          User=root
          Environment=NODE_ENV=production
          Environment=PORT=3000

          [Install]
          WantedBy=multi-user.target
          EOF

          systemctl daemon-reload
          systemctl enable search-web
          systemctl start search-web

Outputs:
  EC2PublicIP:
    Description: "Public IP of the web server"
    Value: !GetAtt WebServerEC2.PublicIp

  EC2InstanceId:
    Value: !Ref WebServerEC2
