AWSTemplateFormatVersion: "2010-09-09"
Description: Rekognition Project - Upload Website (PHP + Nginx)

Parameters:
  ProjectName:
    Type: String

  Environment:
    Type: String

  VPCId:
    Type: String

  PublicSubnetId:
    Type: String

  WebSecurityGroupId:
    Type: String

  EC2KeyPairName:
    Type: String

  GitRepositoryUrl:
    Type: String

  BranchName:
    Type: String
    Default: main

  WebAmiId:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/ami-amazon-linux-latest/al2023-ami-kernel-default-x86_64

Resources:
  UploadWebEC2:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.micro
      ImageId: !Ref WebAmiId
      KeyName: !Ref EC2KeyPairName
      SubnetId: !Ref PublicSubnetId
      SecurityGroupIds:
        - !Ref WebSecurityGroupId
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-${Environment}-upload-web"
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          set -eux

          # MàJ système
          dnf update -y

          # Outils & runtimes
          dnf install -y git nginx php-cli php-fpm php-json php-mbstring php-mysqlnd curl

          systemctl enable php-fpm
          systemctl start php-fpm
          systemctl enable nginx
          systemctl start nginx

          # Déployer l'appli
          mkdir -p /var/www
          cd /var/www
          git clone ${GitRepositoryUrl} rekognition-project
          cd rekognition-project
          git checkout ${BranchName}

          cd apps/upload-web
          curl -sS https://getcomposer.org/installer | php
          php composer.phar install --no-dev

          # Config Nginx pour PHP
          cat >/etc/nginx/nginx.conf <<'EOF'
          user nginx;
          worker_processes auto;

          error_log /var/log/nginx/error.log;
          pid /run/nginx.pid;

          events { worker_connections 1024; }

          http {
              include /etc/nginx/mime.types;
              default_type application/octet-stream;
              sendfile on;

              server {
                  listen 80;
                  server_name _;

                  root /var/www/rekognition-project/apps/upload-web/public;
                  index index.php index.html;

                  location / {
                      try_files $uri /index.php?$query_string;
                  }

                  location ~ \.php$ {
                      fastcgi_pass unix:/run/php-fpm/www.sock;
                      fastcgi_index index.php;
                      include fastcgi_params;
                      fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
                  }
              }
          }
          EOF

          nginx -t
          systemctl restart nginx


Outputs:
  UploadWebPublicIP:
    Value: !GetAtt UploadWebEC2.PublicIp
  UploadWebInstanceId:
    Value: !Ref UploadWebEC2
