AWSTemplateFormatVersion: "2010-09-09"
Description: Rekognition Project - DB Server (MariaDB) in private subnet

Parameters:
  ProjectName:
    Type: String

  Environment:
    Type: String

  VPCId:
    Type: String

  PrivateSubnetId:
    Type: String

  DbSecurityGroupId:
    Type: String

  EC2KeyPairName:
    Type: String

  DbName:
    Type: String
    Default: rekognition_db

  DbUser:
    Type: String
    Default: appuser

  DbPassword:
    Type: String
    NoEcho: true

  WebAmiId:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/ami-amazon-linux-latest/al2023-ami-kernel-default-x86_64

Resources:
  DatabaseEC2:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.micro
      ImageId: !Ref WebAmiId
      KeyName: !Ref EC2KeyPairName
      SubnetId: !Ref PrivateSubnetId          # 🔴 private subnet
      SecurityGroupIds:
        - !Ref DbSecurityGroupId
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-${Environment}-db"
      # Pas de public IP (PrivateSubnet + pas de MapPublicIpOnLaunch)
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          set -eux

          yum update -y
          yum install -y mariadb105-server
          systemctl enable mariadb
          systemctl start mariadb

          mysql -e "ALTER USER 'root'@'localhost' IDENTIFIED BY '${DbPassword}'"
          mysql -uroot -p'${DbPassword}' -e "CREATE DATABASE IF NOT EXISTS \`${DbName}\`"
          mysql -uroot -p'${DbPassword}' -e "CREATE USER IF NOT EXISTS '${DbUser}'@'%' IDENTIFIED BY '${DbPassword}'"
          mysql -uroot -p'${DbPassword}' -e "GRANT ALL PRIVILEGES ON \`${DbName}\`.* TO '${DbUser}'@'%'"
          mysql -uroot -p'${DbPassword}' -e "FLUSH PRIVILEGES"

          mysql -u'${DbUser}' -p'${DbPassword}' '${DbName}' <<'SQL'
          CREATE TABLE IF NOT EXISTS uploads(
            id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
            s3_bucket VARCHAR(255) NOT NULL,
            s3_key TEXT NOT NULL,
            rekognition_faces JSON NULL,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
          ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
          SQL

Outputs:
  DatabasePrivateIP:
    Description: "Private IP of the DB server"
    Value: !GetAtt DatabaseEC2.PrivateIp
